[2020-02-19 21:02:18,484] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=930) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:18,511] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:18,512] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:18,539] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:18,540] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:18,711] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:18,712] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:18,888] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:18,888] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:19,288] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:19,289] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:20,012] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:20,013] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:20,048] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:20,048] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:21,238] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:21,239] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:21,320] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:21,321] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:22,381] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:22,382] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:22,528] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:22,528] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:23,570] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:23,571] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:23,825] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:23,826] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:24,450] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:24,451] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:25,074] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:25,075] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:25,634] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:25,635] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:26,603] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:26,604] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:26,929] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:26,930] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:27,504] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:27,505] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
[2020-02-19 21:02:28,396] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:28,397] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-02-19 21:02:28,462] WARN [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error connecting to node 172.17.156.10:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:283)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:261)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:495)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1300)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:262)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:71)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:337)
[2020-02-19 21:02:28,464] INFO [Consumer clientId=_confluent-license-consumer-0, groupId=null] Error sending fetch request (sessionId=1846320975, epoch=INITIAL) to node 0: {}. (org.apache.kafka.clients.FetchSessionHandler)
org.apache.kafka.common.errors.DisconnectException
